apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filestore-nfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: filestore-nfs-pv
  resources:
    requests:
      storage: 1Ti
